package com.sample
 
import com.sample.DroolsTest.Message;
 
rule "Hello World"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "GoodBye"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end

rule "Boom!" salience 9
	when
		m : Message( message == "boom?" )
	then
		System.out.println("Boom!");
		m.setMessage("Boom!");
		m.setStatus(2);
		update(m);
end